spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.application.name=springboot-mybatis-quickstart
spring.datasource.url=jdbc:mysql://localhost:3306/java147_db02
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=13145
#mybatis????sql????????
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

#??xml?mapper???????
mybatis.mapper-locations=classpath:mapper/*.xml
