spring.application.name=tlias-web-manager

spring.datasource.url=jdbc:mysql://localhost:3306/tlias
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=13145
#mybatis????sql????????
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.configuration.map-underscore-to-camel-case=true

#??spring?????debug??
logging.level.org.springframework.jdbc.support.JdbcTransactionManager=debug

#single file-size default=1MB
spring.servlet.multipart.max-file-size=10MB
#single time file-size default=10MB
spring.servlet.multipart.max-request-size=100MB

#aliyun
aliyun.oss.endpoint=https://oss-cn-beijing.aliyuncs.com
aliyun.oss.bucket=lily-java147
