spring.application.name=tlias-web-manager

spring.datasource.url=jdbc:mysql://localhost:3306/tlias
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=13145
#mybatis????sql????????
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.configuration.map-underscore-to-camel-case=true

mybatis.mapper-locations=classpath:com/lily/mapper/*.xml